export const WMO_CODES = {
    0: { desc: 'Clear Sky', icon: '☀️', night: '🌙' },
    1: { desc: 'Mainly Clear', icon: '🌤️', night: '🌙' },
    2: { desc: 'Partly Cloudy', icon: '⛅', night: '☁️' },
    3: { desc: 'Overcast', icon: '☁️', night: '☁️' },
    45: { desc: 'Foggy', icon: '🌫️', night: '🌫️' },
    48: { desc: 'Rime Fog', icon: '🌫️', night: '🌫️' },
    51: { desc: 'Light Drizzle', icon: '🌦️', night: '🌧️' },
    53: { desc: 'Moderate Drizzle', icon: '🌦️', night: '🌧️' },
    55: { desc: 'Dense Drizzle', icon: '🌧️', night: '🌧️' },
    61: { desc: 'Slight Rain', icon: '🌦️', night: '🌧️' },
    63: { desc: 'Moderate Rain', icon: '🌧️', night: '🌧️' },
    65: { desc: 'Heavy Rain', icon: '🌧️', night: '🌧️' },
    66: { desc: 'Freezing Rain', icon: '🌨️', night: '🌨️' },
    67: { desc: 'Heavy Freezing Rain', icon: '🌨️', night: '🌨️' },
    71: { desc: 'Slight Snow', icon: '🌨️', night: '🌨️' },
    73: { desc: 'Moderate Snow', icon: '❄️', night: '❄️' },
    75: { desc: 'Heavy Snow', icon: '❄️', night: '❄️' },
    77: { desc: 'Snow Grains', icon: '🌨️', night: '🌨️' },
    80: { desc: 'Rain Showers', icon: '🌦️', night: '🌧️' },
    81: { desc: 'Moderate Showers', icon: '🌧️', night: '🌧️' },
    82: { desc: 'Violent Showers', icon: '⛈️', night: '⛈️' },
    85: { desc: 'Snow Showers', icon: '🌨️', night: '🌨️' },
    86: { desc: 'Heavy Snow Showers', icon: '❄️', night: '❄️' },
    95: { desc: 'Thunderstorm', icon: '⛈️', night: '⛈️' },
    96: { desc: 'Thunderstorm + Hail', icon: '⛈️', night: '⛈️' },
    99: { desc: 'Severe Thunderstorm', icon: '⛈️', night: '⛈️' },
};
